version: '3.8'

services:
  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
#      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "55679:55679" # zpages extension
      - "14250:14250" # Jaeger gRPC
      - "14268:14268" # Jaeger HTTP thrift
      - "9411:9411"   # Zipkin
#    depends_on:
#      - jaeger
#      - prometheus
    networks:
      - otel-network

  # Jaeger
#  jaeger:
#    image: jaegertracing/all-in-one:latest
#    container_name: jaeger
#    ports:
#      - "16686:16686" # Jaeger UI
#      - "14269:14269" # Admin port
#    environment:
#      - COLLECTOR_OTLP_ENABLED=true
#    networks:
#      - otel-network

  # Prometheus
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
#    command:
#      - --config.file=/etc/prometheus/prometheus.yml
#      - --storage.tsdb.path=/prometheus
#      - --web.console.libraries=/etc/prometheus/console_libraries
#      - --web.console.templates=/etc/prometheus/consoles
#      - --web.enable-lifecycle
#    networks:
#      - otel-network

  # Grafana (可選)
#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#    volumes:
#      - grafana-storage:/var/lib/grafana
#      - ./grafana/provisioning:/etc/grafana/provisioning:ro
#    networks:
#      - otel-network

networks:
  otel-network:
    external: true

#volumes:
#  grafana-storage: