# otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_http:
        endpoint: 0.0.0.0:14268

  zipkin:
    endpoint: 0.0.0.0:9411

  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: [ '0.0.0.0:8888' ]

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  resource:
    attributes:
      - key: environment
        value: "development"
        action: upsert

  memory_limiter:
    limit_mib: 1000

# 輸出metric
exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

  logging:
    loglevel: debug

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

  pprof:
    endpoint: 0.0.0.0:1888

  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [ health_check, pprof, zpages ]

  pipelines:
    traces:
      receivers: [ otlp, jaeger, zipkin ]
      processors: [ memory_limiter, resource, batch ]
      exporters: [ jaeger, logging ]

    metrics:
      receivers: [ otlp, prometheus ]
      processors: [ memory_limiter, resource, batch ]
      exporters: [ prometheus, logging ]

    logs:
      receivers: [ otlp ]
      processors: [ memory_limiter, resource, batch ]
      exporters: [ logging ]

  telemetry:
    logs:
      level: "debug"