receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  # 發送追蹤數據到 Tempo
  otlp/tempo:
    endpoint: http://tempo:4317
    tls:
      insecure: true

  # 發送日誌到 Loki
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  # 發送指標到 Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/tempo ]

    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ loki ]

    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheus ]